server:
  port: 9091 #服务端口
spring:
  application:
    name: provider  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    username: root
    password: wjq.19980408
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:dao/*.xml
  type-aliases-package: com.nacos.common.pojo